spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?serverTimezone=UTC&useUnicode=true&character=UTF-8
    username: root
    password: 549541995tsg
    driver-class-name: com.mysql.cj.jdbc.Driver
